development:
  shopify_api_key: "38607e480f7260554172b711c1c10502"
  shopify_secret: "ec2f76c4b87e5a0022f10f128e6c19b4"
  ups_user_id: 'jnatowitz@lapineinc.com'
  ups_password: 'P444word!'
  ups_key: 'ACD8A71E16D5BA35'
  app_url: 'http://localhost:3000'
production:
  shopify_api_key: "38607e480f7260554172b711c1c10502"
  shopify_secret: "ec2f76c4b87e5a0022f10f128e6c19b4"
  ups_user_id: 'jnatowitz@lapineinc.com'
  ups_password: 'P444word!'
  ups_key: 'ACD8A71E16D5BA35'
  app_url: 'https://fissler-b2b-shipping-rate.herokuapp.com/'