development:
  shopify_api_key: "2b840eea299738a7603e7932774bcc83"
  shopify_secret: "18338ce321cf50e57a52130cbe712571"
  ups_user_id: 'jnatowitz@lapineinc.com'
  ups_password: 'P444word!'
  ups_key: 'ACD8A71E16D5BA35'
  app_url: 'http://localhost:3000'
production:
  shopify_api_key: "2b840eea299738a7603e7932774bcc83"
  shopify_secret: "18338ce321cf50e57a52130cbe712571"
  ups_user_id: 'jnatowitz@lapineinc.com'
  ups_password: 'P444word!'
  ups_key: 'ACD8A71E16D5BA35'
  app_url: 'https://shipping-custom-rate.herokuapp.com'