development:
  shopify_api_key: "499a3cf2d0ae935f97b0802e7080ac6a"
  shopify_secret: "22f8a9dc6c9ca1bae955c291ddbbadbc"
  ups_user_id: 'jnatowitz@lapineinc.com'
  ups_password: 'P444word!'
  ups_key: 'ACD8A71E16D5BA35'
  app_url: 'http://localhost:3000'
production:
  shopify_api_key: "499a3cf2d0ae935f97b0802e7080ac6a"
  shopify_secret: "22f8a9dc6c9ca1bae955c291ddbbadbc"
  ups_user_id: 'jnatowitz@lapineinc.com'
  ups_password: 'P444word!'
  ups_key: 'ACD8A71E16D5BA35'
  app_url: 'https://customshippingapp.com/'